### ISSUE TITLE
PaymentIntents Precondition failed -> NIO crash

### ISSUE THREAD

**Issue by apps4everyone** [vapor-community/stripe-kit#100]
Using latest Vapor 4.27.1 and NIO 2.20.2 there is a Crash with this message:
Precondition failed: file /{PATH_TO_PROJECT}/.build/checkouts/swift-nio/Sources/NIO/ChannelPipeline.swift, line 1416

`
func createPaymentIntent(req: Request) throws -> EventLoopFuture<PaymentIntentResponse> {
    
        guard let paymentIntentRequest: PaymentIntentRequest = try? req.content.decode(PaymentIntentRequest.self) else {
            throw Abort(.notFound)
        }
        
        return req.stripe.paymentIntents.create(amount: self.calculateOrderAmount(paymentIntentRequest: paymentIntentRequest),
                                                    currency: .eur,
                                                    applicationFeeAmount: nil,
                                                    captureMethod: nil,
                                                    confirm: nil,
                                                    confirmationMethod: nil,
                                                    customer: nil,
                                                    description: nil,
                                                    errorOnRequiresAction: nil,
                                                    mandate: nil,
                                                    mandateData: nil,
                                                    metadata: nil,
                                                    offSession: nil,
                                                    onBehalfOf: nil,
                                                    paymentMethod: nil,
                                                    paymentMethodData: nil,
                                                    paymentMethodOptions: nil,
                                                    paymentMethodTypes: nil,
                                                    receiptEmail: nil,
                                                    returnUrl: nil,
                                                    savePaymentMethod: nil,
                                                    setupFutureUsage: nil,
                                                    shipping: nil,
                                                    statementDescriptor: nil,
                                                    statementDescriptorSuffix: nil,
                                                    transferData: nil,
                                                    transferGroup: nil,
                                                    useStripeSDK: nil,
                                                    expand: nil)
            .map { paymentIntent in
                          
                debugPrint(paymentIntent.id)
                return PaymentIntentResponse(clientSecret: paymentIntent.clientSecret)
        }
    }
    
    private func calculateOrderAmount(paymentIntentRequest: PaymentIntentRequest) -> Int {
        
        // TODO: calculate price
        return 100
    }
`

**Comment by Andrewangeta** [comment]
I'm not sure what the error is. How is this related to stripe exactly? Gonna need some more info. @apps4everyone

**Comment by apps4everyone** [comment]
Hey @Andrewangeta, thx for your quick reply. If I am using a fresh new vapor installation with just one route /create-payment-intent (as mentioned in the stripe example on the website) and call this API from my mobile app every 2-4 times Vapor crashes with this example above.

**Comment by Andrewangeta** [comment]
You'll need to provide some more info. Have you stepped through the debugger to see what line is causing the crash? The crash is in NIO but the snippet you have isn't helping.

**Comment by apps4everyone** [comment]
it looks like the problem was the missing promise. If I use:
let promise = req.eventLoop.makePromise(of: PaymentIntentResponse.self) and do then the 'req.stripe.paymentIntents.create' everything looks good so far. I will test tomorrow and if there is no more problems i will close this ticket. thx for your help...

**Comment by Andrewangeta** [comment]
@apps4everyone Also you don't need to have all the `nil`s in the route. They have default values.
