### ISSUE TITLE
Decoding error with Payment Intent

### ISSUE THREAD

**Issue by juanLovera** [vapor-community/stripe-kit#121]
Stripe is returning 'fail' instead of 'failed' for StripeCardValidationCheck. 

StripeKit is expecting 'failed':
<img width="537" alt="Screen Shot 2021-04-08 at 9 13 08 PM" src="https://user-images.githubusercontent.com/4535491/114111006-48064000-98af-11eb-9f84-1aab33f19aca.png">

But Stripe sends 'fail'. Example (/v1/payment_intents):
<img width="347" alt="Screen Shot 2021-04-08 at 9 12 33 PM" src="https://user-images.githubusercontent.com/4535491/114110976-30c75280-98af-11eb-96cd-b62ea3003e57.png">
Documentation:
<img width="497" alt="Screen Shot 2021-04-08 at 9 17 14 PM" src="https://user-images.githubusercontent.com/4535491/114111380-4a1cce80-98b0-11eb-883b-904c736ba98e.png">

Exception:
dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "charges", intValue: nil), CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "paymentMethodDetails", intValue: nil), CodingKeys(stringValue: "card", intValue: nil), CodingKeys(stringValue: "checks", intValue: nil), CodingKeys(stringValue: "addressLine1Check", intValue: nil)], debugDescription: "Cannot initialize StripeCardValidationCheck from invalid String value fail", underlyingError: nil))

Thanks

**Comment by Andrewangeta** [comment]
@juanLovera This should be available now. Just reset your package cache and it should pull in the latest version.

**Comment by juanLovera** [comment]
@Andrewangeta Thanks for the quick resolution 🙌
