### ISSUE TITLE
JSON decoding error in StripeSource

### ISSUE THREAD

**Issue by varungakhar** [vapor-community/stripe-kit#123]
let future = req.stripe.sources.attach(source: requestmodel.card_token!, customer: customer_id)
future.whenFailure { (error)
 req.logger.info("\(error.debugDescription)")
}

[ INFO ] Swift.DecodingError.valueNotFound(Swift.Double, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "super", intValue: nil)], debugDescription: "Expected Double but found null value instead.", underlyingError: nil)) [request-id: EF3EEC1F-1E19-4EE3-855C-34FE32B6A49B]

Using above code to attach card to stripe customer. I am able to see card attached on stripe dashboard but getting this error. 

Thank You.

**Comment by Andrewangeta** [comment]
What version of StripeKit are you using? And what's the expected response you're looking for?

**Comment by varungakhar** [comment]
i am using latest version. 
future.whenSuccess { (source) in
                let success = SuccessError<StripeRequestModel>(success: true, code: 200, message:"Success!!")
                promise.succeed(success)
            }

Future should return STPSource object . It is giving json decode error , always fall in error clouser . 
Here's json of future response . It does not have {created} key , making it optional will resolve this issue.

{"address_line1_check":null,"dynamic_last4":null,"last4":"5556","address_line2":null,"metadata":{},"address_city":null,"address_zip_check":null,"address_zip":null,"country":"US","object":"card","address_line1":null,"address_state":null,"brand":"Visa","cvc_check":null,"exp_month":4,"name":null,"fingerprint":"zNTczFeWV25PzE2P","funding":"debit","id":"card_1IfoneLKexXnVdcpT166XC1e","tokenization_method":null,"customer":"cus_JGRHrPDez6RyjE","address_country":null,"exp_year":2022}
![Screenshot 2021-04-13 at 9 22 16 PM](https://user-images.githubusercontent.com/12067480/114588365-3d2f1f00-9ca4-11eb-8f03-b9cde4718284.png)

**Comment by Andrewangeta** [comment]
That’s a `card` object you’re getting back, not a source. 
https://stripe.com/docs/api/cards/object
The source object is returned for attaching a source which has a `created` property 
https://stripe.com/docs/api/sources/attach

**Comment by Andrewangeta** [comment]
Can you show the actual route and use swift formatting so it’s readable to see what’s going on.

**Comment by varungakhar** [comment]
> Can you show the actual route and use swift formatting so it’s readable to see what’s going on.

https://api.stripe.com/v1/customers/cus_JGRHrPDez6RyjE/sources

**Comment by varungakhar** [comment]
> That’s a `card` object you’re getting back, not a source.
> https://stripe.com/docs/api/cards/object
> The source object is returned for attaching a source which has a `created` property
> https://stripe.com/docs/api/sources/attach

yes, I am sending card token {tok_visa_debit} not source token

**Comment by varungakhar** [comment]
I am facing another issues. I have added two cards against a customer id, able to see the cards on dashboard but when i try to access through "req.stripe.customers.retrieve(customer: requestmodel.customer_id!)"  it is not returning any source. 
<img width="1171" alt="Screenshot 2021-04-14 at 1 16 22 PM" src="https://user-images.githubusercontent.com/12067480/114673312-ac982380-9d23-11eb-980f-442bee9c33c0.png">

**Comment by Andrewangeta** [comment]
You can expand the default source. Otherwise it's the the source id

**Comment by varungakhar** [comment]
Thanks for the help 👍
