### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by siciliano2281** [vapor-community/stripe-kit#128]
_I receive the following error in the console:_ 

`Assertion failed: file AsyncHTTPClient/HTTPClient.swift, line 117
2021-05-06 16:19:12.537202-0400 Run[9051:882865] Assertion failed: file AsyncHTTPClient/HTTPClient.swift, line 117`

_when running the following code:_

`
func createCustomerStripe(_ req: Request) throws -> EventLoopFuture<StripeCustomer> {
        
        print("createCustomerStripe called.")
        
        let customerFromClient = try req.content.decode(CustomersDTO.self)

        let httpClient = HTTPClient(eventLoopGroupProvider: .shared(req.eventLoop))
        let stripe = StripeClient(httpClient: httpClient, eventLoop: req.eventLoop, apiKey: "test_key")
        
        let newCustomer = stripe.customers.create(email: customerFromClient.email,
                                                  name: customerFromClient.name,
                                                  phone: customerFromClient.phone)
        
        return newCustomer
    }
`

**IMPORTANT**: Stripe receives each new customer when this func is called. A new customer is created with the data submitted (email, name, phone). Stripe Logs show no errors. However, Vapor crashes. Please help!

**Comment by Andrewangeta** [comment]
I recommend using the [Stripe Vapor package](https://github.com/vapor-community/stripe) vs Stripe-Kit directly. But essentially you're not hopping to the requests event loop with the stripe client.

**Comment by siciliano2281** [comment]
OK, should I remove the Stripe-Kit package?

**Comment by Andrewangeta** [comment]
Yes

**Comment by siciliano2281** [comment]
Got it, thanks for the help
