### ISSUE TITLE
Not returning JSON - Creating a Stripe Connect Account

### ISSUE THREAD

**Issue by siciliano2281** [vapor-community/stripe-kit#129]
Hi everyone. I'm having trouble with my route that handles the onboarding of a user. With a POST call, I create a new Stripe Connect Account with confirmation on Stripe's logs. However, I do not receive any JSON in response to this POST. Stripe's logs show that the response is JSON with all relevant parameters attached to this new Stripe Connect Account. I have triple-checked the model that decodes the JSON. The same HTTP request made in Postman yields a response that contains email in the POST request (not JSON). 

I have determined that the problem must exist on my server because 1) my client reads an error that the data received was not valid JSON, and 2) Stripe's logs show that the response to the POST is JSON.

I have attached my Vapor code below. I know that I am not implementing the proper return because whatever is being returned is not JSON. This is strange as the AccountRoutes.swift found in Stripe Kit show that the return to a create function is a `StripeConnectAccount`. Thank you for the help in advance!

`func createStripeConnectAccount(_ req: Request) throws -> EventLoopFuture<StripeConnectAccount> {
        
        print("createStripeAccount called.")
        
        let stripeAccountInput = try req.content.decode(AccountDTO.self)
        
        let newStripeAccount = req.stripe.connectAccounts.create(
                                                            type: .express,
                                                            country: "US",
                                                            email: stripeAccountInput.email,
                                                            businessType: .individual,
                                                            defaultCurrency: .usd,
                                                            metadata: [
                                                                "licensePlate": stripeAccountInput.licensePlate,
                                                                "username": stripeAccountInput.username,
                                                            ],
                                                            capabilities: [:]
                                                            )
        
        return newStripeAccount
    }`

Best,
Jake

**Comment by Andrewangeta** [comment]
Did you try to hit the vapor route via postman?

**Comment by siciliano2281** [comment]
Yes, I ran the url on Postman to hit the route. The url is identical to that run on my client (http://<myNgrokURL>/stripeConnectAccount where /stripeConnectAccount is a route grouping in my Route controller for Stripe API calls). The response wasn't JSON and it was just the email submitted in the POST.

Did I implement the return properly?

**Comment by Andrewangeta** [comment]
What was the response?

**Comment by siciliano2281** [comment]
<img width="1792" alt="Screen Shot 2021-05-25 at 11 49 47 AM" src="https://user-images.githubusercontent.com/78518998/119528862-8ff20100-bd4f-11eb-8ff9-ac549814b83c.png">

**Comment by Andrewangeta** [comment]
Can you show the actual swift code you're using?

**Comment by siciliano2281** [comment]
My swift code on my client:

`func createStripeAccountCall(completion: @escaping () -> ()) {
            do {
                let url = URL(string: "\(Constants.baseURLString)/stripeConnectAccount")
                var urlReq = URLRequest(url: url!)
                urlReq.setValue("application/json", forHTTPHeaderField: "Content-Type")
                urlReq.httpMethod = "POST"
                
                let encoder = JSONEncoder()
                
                let newStripeAccount = StripeCreateAccount(id: UUID(),
                                                        email: UserDefaults.standard.string(forKey: "createEmail")!,
                                                        licensePlate: UserDefaults.standard.string(forKey: "createLicensePlate")!,
                                                        username: UserDefaults.standard.string(forKey: "createUserName")!)
                
                let payload = try encoder.encode(newStripeAccount)
                
                let result = URLSession.shared.uploadTask(with: urlReq, from: payload) { (data, resp, err) in
                    
                    guard let gotData = data else {
                        print("register failed!")
                        return
                    }
                    
                    let decoder = JSONDecoder()
                    let stripeMe = try? decoder.decode(StripeMe.self, from: gotData)
                    
                    print("register attempt complete.")
                    DispatchQueue.main.async {
                        
                        self.stripeMe = stripeMe
                        print("stripeMe = \(stripeMe ?? nil)")
                        completion()
                    }
                }
                result.resume()
                print("result = \(result)")
            } catch {
            print("register failed during network call!")
            }
        }`

This isn't the problem, as Postman shows a non-JSON response as well. I'm not implementing something on the server properly.

**Comment by Andrewangeta** [comment]
I meant the vapor code in its entirety not the iOS code

**Comment by siciliano2281** [comment]
The route controller code:

`
func boot(routes: RoutesBuilder) throws {
let stripeAccount = routes.grouped("stripeConnectAccount")
            
        stripeAccount.post(use: createStripeConnectAccount)
}
`

The DTO used to decode the POST's content:

`struct AccountDTO: Content {
    
    var email: String
    var licensePlate: String
    var username: String
}
`

What portions of the code do you want? To reiterate, Stripe receives my POST and populates the parameters of a new Connect Account with the content submitted.

**Comment by Andrewangeta** [comment]
I wanna see the actual route code.

**Comment by Andrewangeta** [comment]
Show a picture of it

**Comment by siciliano2281** [comment]
boot func:
![IMG_0714](https://user-images.githubusercontent.com/78518998/119541670-aeaac480-bd5c-11eb-96df-553b0648b992.jpeg)

Stripe call func:
![IMG_0715](https://user-images.githubusercontent.com/78518998/119541879-eca7e880-bd5c-11eb-90de-a9c173aaed66.jpeg)

**Comment by Andrewangeta** [comment]
How are you encoding the response?
Can you do a `.map` and print out the connect account or at least inspect it and make sure it has all the properties.
Also stripe's decoder converts from snake case so make you're using a decoder that doesn't account for that when returning.

**Comment by siciliano2281** [comment]
Hey Andrew. `.map` did the trick. I was able to map onto a model and the model prints as JSON for me. Thanks for the help!

Best,
Jake
