### ISSUE TITLE
Webhook events for Stripe Identity

### ISSUE THREAD

**Issue by kschins** [vapor-community/stripe-kit#135]
Are there plans to add the new webhook events for Stripe Identity?

- identity.verification_session.canceled
- identity.verification_session.created
- identity.verification_session.processing
- identity.verification_session.redacted
- identity.verification_session.requires_input
- identity.verification_session.verified

If there is no timeline, I can attempt to implement this and create a PR.

**Comment by Andrewangeta** [comment]
@kschins they're already implemented. Was part of the 13.0.0 release https://github.com/vapor-community/stripe-kit/blob/52af608107dbae65168a0bd6b8210f690c0762d0/Sources/StripeKit/Core%20Resources/Events/Event.swift#L328

**Comment by kschins** [comment]
@Andrewangeta doh, sorry about that -- wasn't looking at the latest version. Thank you!

**Comment by Andrewangeta** [comment]
Actually the event keys are there but I don’t think they’re implemented with decoding the object. Let me verify

**Comment by Andrewangeta** [comment]
Ok it is implemented. StripeVerificationSession is there!

**Comment by Andrewangeta** [comment]
So you’d do something like 
```swift
switch (event.type, event.data?.object) {
    case (.identityVerificationSessionCreated, .verificationSession(let session)):

```

**Comment by kschins** [comment]
Yup, got it. I have other events implemented so I'm familiar with it -- thanks again.
