### ISSUE TITLE
Error decoding response when retrieving a price for a product.

### ISSUE THREAD

**Issue by cavnit** [vapor-community/stripe-kit#212]
There seems to be an error decoding the Stripe response when calling 

`try await req.stripe.prices.listAll(filter: ["product": "prod_id"])`

The decode error is as follows

`Data corrupted at path 'data.Index 0.unitAmountDecimal'. Cannot initialize PriceTaxBehavior from invalid String value 49000`

unitAmounDecimal is returned as a string, yet it looks like Stripe-Kit is trying to decode it using PriceTaxBehavior

**Comment by Andrewangeta** [comment]
@cavnit Which version of stripekit are you using?

**Comment by cavnit** [comment]
Hi, sorry, latest version 18.1.0

`unitAmountDecimal` is set to `PriceTaxBehavior`, but Stripe definitely returns it as a String(https://stripe.com/docs/api/prices/object#price_object-unit_amount_decimal): 
https://github.com/vapor-community/stripe-kit/blob/85c3d68de8cd6f13064d0a1db6b0d75ee56e8033/Sources/StripeKit/Products/Prices/Price.swift#L53

`PriceTaxBehavior` is an enum https://github.com/vapor-community/stripe-kit/blob/85c3d68de8cd6f13064d0a1db6b0d75ee56e8033/Sources/StripeKit/Products/Prices/Price.swift#L180
