### ISSUE TITLE
SwiftCrypto Platform Version Issue

### ISSUE THREAD

**Issue by HarRes123** [vapor-community/stripe-kit#214]
There is an issue with the SwiftCrypto package dependency. It requires minimum deployment target of iOS 13.0, but StripeKit only requires 11.0. I'm unable to use the package as a result of this, so I'm hoping it can be fixed as soon as possible.

**Comment by tomo2403** [comment]
It does compile now. Thanks!

**Comment by Andrewangeta** [comment]
Fixed with #215
