### ISSUE TITLE
US Bank Account Enum for Charges

### ISSUE THREAD

**Issue by cavnit** [vapor-community/stripe-kit#220]
Currently decoding a Stripe Charge sent via a webhook will fail if the charge is paid via a US Bank Account direct Debit, as the enum does not exist for decoding the value

**Comment by Andrewangeta** [comment]
@cavnit Which version of stripekit are you using? [Ach debit](https://github.com/vapor-community/stripe-kit/blob/f3b66204c817da8a2425c0853c6a0505e97b6793/Sources/StripeKit/Core%20Resources/Charges/Charge.swift#L348) As well as [US bank account](https://github.com/vapor-community/stripe-kit/blob/f3b66204c817da8a2425c0853c6a0505e97b6793/Sources/StripeKit/Core%20Resources/Charges/Charge.swift#L410) are payment methods that exist on the payment method details property of the charge.

**Comment by cavnit** [comment]
I was using [18.1.1](https://github.com/vapor-community/stripe-kit/releases/tag/18.1.1), which I had to fork to add it, and based on the 4 commits since then it is still not there

**Comment by Andrewangeta** [comment]
@cavnit I see. Looks like the [docs are out of date](https://stripe.com/docs/api/charges/object#charge_object-payment_method_details-type) I'll let stripe know and update these types
