### ISSUE TITLE
Ephemeral Keys?

### ISSUE THREAD

**Issue by amkomatz** [vapor-community/stripe-kit#222]
Hey, I'm reading through this documentation, trying to create ephemeral keys for a customer to use with a payment intent. I'm not seeing any reference to ephemeral keys in this package though. Does it exists? Or should I accomplish this some other way? Thanks!

https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet

**Comment by Andrewangeta** [comment]
@amkomatz Stripe doesn't officially document the ephemeral key API in the docs https://stripe.com/docs/api 
A solution could be to check the other libraries and add an API to StripeKit based on the implementation other libraries have. I'll add soon here.

**Comment by amkomatz** [comment]
Wow, thanks for the speedy update!
