### ISSUE TITLE
Cannot retrieve connected account (using old URL)

### ISSUE THREAD

**Issue by Steven4294** [vapor-community/stripe-kit#243]
`let account = try await stripe.connectAccounts.retrieve(account: account_id)`

this throws error:

```
"Unrecognized request URL (GET: /v1/accounts/). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/."
```

**Comment by Andrewangeta** [comment]
@Steven4294 I'm confused, this code works fine for me. Make sure you have an actual account id you pass in and not an empty string

**Comment by Steven4294** [comment]
I will re-review, it's possible it was failing due to an improper account_id being passed in

**Comment by Steven4294** [comment]
C
