### ISSUE TITLE
Missing enum on PaymentMethodCardNetwork

### ISSUE THREAD

**Issue by Steven4294** [vapor-community/stripe-kit#247]
Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "card", intValue: nil), CodingKeys(stringValue: "network", intValue: nil)], debugDescription: "Cannot initialize PaymentMethodCardNetwork from invalid String value eftpos_au", underlyingError: nil))

I believe a more stable solution here would be to have a default field or make the field optional so that decoding doesnt fail if a new field is added by Stripe.

**Comment by Andrewangeta** [comment]
Fixed in #248 Tagged in 22.2.1
