### ISSUE TITLE
Initializers for models?

### ISSUE THREAD

**Issue by Andrewangeta** [vapor-community/stripe-kit#34]
It would be helpful if you could create a Stripe model (`StripeCustomer` for example) with an initializer. Although all of the models right now are `structs`, one easy way in Xcode to generate initializers is to make them classes temporarily and generate member wise initializer.

<img width="765" alt="Screen Shot 2020-02-13 at 6 59 53 PM" src="https://user-images.githubusercontent.com/12012815/74489380-24a25980-4e93-11ea-9091-c5f431a8e36f.png">

Will result in the following initializer.
Note we don't automatically get default nil values in the initializers.

<img width="1670" alt="Screen Shot 2020-02-13 at 7 00 18 PM" src="https://user-images.githubusercontent.com/12012815/74489399-2ec45800-4e93-11ea-8eab-0cb5d57f7c60.png">

This is easy but takes time is all.

**Comment by Maxim-Inv** [comment]
@Andrewangeta Does it need to make for all classes inherited from StipeModel protocol?

**Comment by Andrewangeta** [comment]
> @Andrewangeta Does it need to make for all classes inherited from StipeModel protocol?

Yea we still need to conform to that protocol because of the generic sending of the stripe request. My thinking is that we temporarily make them classes to generate the initializer and then make them structs again afterwards.

**Comment by Andrewangeta** [comment]
As an update Xcode 11.4 now can generate memberwise initializers from structs and also populates default values parameters. 

![memberwise-init](https://user-images.githubusercontent.com/12012815/78626498-ef940100-785c-11ea-98bd-a5ed2e0612f9.gif)

**Comment by Andrewangeta** [comment]
Being addressed by #152
